export type { SidebarBehaviorMode } from "../../../afenda-ui/sidebar-behavior";
export { AfendaAppShell } from "./app-shell";
export {
  APP_SHELL_FOOTER_HEIGHT,
  APP_SHELL_RAIL_WIDTH,
  APP_SHELL_SIDEBAR_ICON_RAIL_WIDTH,
  APP_SHELL_SIDEBAR_WIDTH,
  APP_SHELL_TOPBAR_HEIGHT,
} from "./app-shell-recipes";
export {
  AppShellSidebarProvider,
  useAppShellSidebar,
} from "./app-shell-sidebar-context";
export {
  resolveAppShellSidebarActiveWidth,
  resolveAppShellSidebarExpanded,
} from "./app-shell-sidebar-utils";
export type {
  AfendaAppContentBottomDrawerProps,
  AfendaAppContentBreadcrumbItem,
  AfendaAppContentCssVars,
  AfendaAppContentHeaderProps,
  AfendaAppContentLayoutState,
  AfendaAppContentLeftRailProps,
  AfendaAppContentProps,
  AfendaAppContentRightRailProps,
  AfendaAppFooterProps,
  AfendaAppShellCssVars,
  AfendaAppShellFooterLink,
  AfendaAppShellProps,
  AfendaAppShellSidebarState,
  AfendaAppShellUserSummary,
  AfendaAppSidebarNavGroup,
  AfendaAppSidebarNavGroupDescriptor,
  AfendaAppSidebarNavGroupSlot,
  AfendaAppSidebarNavIconDescriptor,
  AfendaAppSidebarNavIconItem,
  AfendaAppSidebarNavIconKeysOf,
  AfendaAppSidebarNavIconRegistry,
  AfendaAppSidebarNavItem,
  AfendaAppSidebarNavItemDescriptor,
  AfendaAppSidebarNavLayout,
  AfendaAppSidebarNavLayoutDescriptor,
  AfendaAppSidebarNavProductDescriptor,
  AfendaAppSidebarNavProductItem,
  AfendaAppSidebarProps,
  AfendaAppTopbarProps,
  AfendaTopbarUtilitiesController,
  AppSidebarNavIconItem,
  AppSidebarNavItem,
  AppSidebarNavProductItem,
  SidebarNavUserActionMenuItem,
  SidebarNavUserLinkMenuItem,
  SidebarNavUserMenuGroup,
  SidebarNavUserMenuItem,
  SidebarNavUserProps,
  TopbarActionsMenuGroup,
  TopbarActionsMenuItem,
  TopbarActionsMenuProps,
  TopbarBrandDiskProps,
  TopbarContextOption,
  TopbarContextScope,
  TopbarContextSwitcherProps,
  TopbarRightActionsProps,
  TopbarUtilitiesScope,
  TopbarUtilitiesState,
  TopbarUtilityId,
} from "./app-shell-types";
export {
  AfendaAppContent,
  AfendaAppContentBottomDrawer,
  AfendaAppContentHeader,
  AfendaAppContentLayoutProvider,
  AfendaAppContentLeftRail,
  AfendaAppContentRightRail,
  useAfendaAppContentLayout,
} from "./content";
export { AfendaAppFooter } from "./footer";
export {
  AfendaAppSidebar,
  collectSidebarNavItemDescriptors,
  collectSidebarNavItems,
  defaultSidebarLink,
  resolveActiveSidebarNavItemId,
  resolveActiveSidebarNavItemIds,
  resolveAfendaAppSidebarNavItemDescriptor,
  resolveAfendaAppSidebarNavLayout,
  resolveSidebarLinkRenderer,
  SidebarNavUser,
  type SidebarLinkRenderProps,
  type SidebarLinkRenderer,
} from "./sidebar";
export { sidebarLinkClass } from "./sidebar/sidebar-nav-recipes";
export {
  AfendaAppTopbar,
  TOPBAR_UTILITY_CATALOG,
  TOPBAR_UTILITY_DEFAULT_PINNED,
  TOPBAR_UTILITY_MAX_PINNED,
  TopbarActionsMenu,
  TopbarBrandDisk,
  TopbarContextSwitcher,
  TopbarRightActions,
  TopbarScopeSwitchers,
  TopbarSidebarControl,
  TopbarSidebarTrigger,
  TopbarThemeToggle,
  TopbarUtilitiesBar,
  TopbarUtilitiesMarketplace,
  TopbarUtilitiesProvider,
  useTopbarUtilities,
} from "./topbar";
