export const AFENDA_RECIPE_IDENTITY_REGISTRY = [
  "bodyText",
  "bodyMediumText",
  "controlText",
  "buttonText",
  "labelText",
  "titleText",
  "captionText",
  "metadataText",
  "badgeText",
  "shortcutText",
  "visuallyHidden",
  "accordionTriggerLabel",
  "focusRing",
  "focusRingOnly",
  "invalidState",
  "disabledAction",
  "disabledControl",
  "readOnlyControl",
  "motionReduce",
  "colorTransition",
  "interactiveTransition",
  "controlSurface",
  "flatControlSurface",
  "overlaySurface",
  "panelSurface",
  "modalSurface",
  "controlDefaultSize",
  "controlCompactSize",
  "controlLargeSize",
  "rowItem",
  "rowInset",
  "rowHighlight",
  "rowDisabled",
  "rowCritical",
  "rowCheckboxPadding",
  "rowIcon",
  "rowCriticalIcon",
  "controlIcon",
  "mutedControlIcon",
  "accordionTriggerIcon",
  "breadcrumbEllipsisIcon",
  "calendarWeekNumberCell",
  "chartTooltipItems",
  "chartTooltipIndicator",
  "chartTooltipIndicatorDot",
  "chartTooltipIndicatorLine",
  "chartTooltipIndicatorDashed",
  "chartTooltipIndicatorNested",
  "chartTooltipName",
  "chartTooltipValue",
  "chartLegendItem",
  "chartLegendSwatch",
  "checkboxIndicator",
  "checkboxCheckIcon",
  "checkboxIndeterminateIcon",
  "commandInputWrapper",
  "commandInputIcon",
  "commandGroup",
  "fieldSeparatorContent",
  "fieldErrorList",
  "overlayMotion",
  "popoverOrigin",
  "dropdownOrigin",
  "selectOrigin",
  "modalBackdrop",
  "modalHeader",
  "modalFooter",
  "dismissButton",
  "menuLabelInset",
  "menuSeparator",
  "menuSeparatorInset",
  "itemIndicator",
  "itemIndicatorCheckIcon",
  "itemIndicatorRadioIcon",
  "submenuChevronIcon",
  "navigationMenuTriggerIcon",
  "navigationMenuViewportWrapper",
  "navigationMenuIndicatorArrow",
  "paginationIcon",
  "radioGroupIndicator",
  "radioGroupIndicatorIcon",
  "resizableHandleIcon",
  "scrollAreaCorner",
  "scrollAreaThumb",
  "selectIcon",
  "selectItemIndicator",
  "sliderTrack",
  "sliderRange",
  "sliderThumb",
  "tooltipArrow",
  "toasterRoot",
  "toastSuccessIcon",
  "toastInfoIcon",
  "toastWarningIcon",
  "toastCriticalIcon",
  "toastLoadingIcon",
  "sidebarTooltipLabel",
  "sidebarTooltipDescription",
  "sidebarTooltipShortcut",
  "sidebarMobileSheetContent",
  "sidebarRootPeer",
  "sidebarControlIcon",
  "sidebarControlMenuLabel",
  "sidebarControlMenuItem",
  "sidebarMenuButtonSmallText",
  "sidebarTooltipContent",
  "sidebarMenuSkeletonIcon",
  "sidebarMenuSubButtonSmallText",
  "sidebarMenuSubButtonDefaultText",
  "itemIndicatorMuted",
  "overlayScrollButton",
  "overlayPadding",
  "menuPadding",
  "panelPadding",
  "modalPadding",
  "fieldGap",
  "sectionGap",
] as const;

export type AfendaRecipeIdentity =
  (typeof AFENDA_RECIPE_IDENTITY_REGISTRY)[number];

export const AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY = [
  "blockShell",
  "blockStack",
  "blockHeader",
  "blockHeaderContent",
  "blockTitle",
  "blockDescription",
  "blockToolbar",
  "blockPanel",
  "blockPanelPadding",
  "blockSection",
  "blockSectionDivider",
  "blockMetric",
  "blockMetricLabel",
  "blockEmpty",
  "blockCompact",
  "blockComfortable",
  "blockChrome",
  "blockRail",
  "blockStage",
] as const;

export type AfendaBlockRecipeIdentity =
  (typeof AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY)[number];

export const AFENDA_RECIPE_REGISTRY = [
  ...AFENDA_RECIPE_IDENTITY_REGISTRY,
  ...AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY,
] as const;

export type AfendaRecipeRegistryIdentity =
  (typeof AFENDA_RECIPE_REGISTRY)[number];

export const afendaRecipeRegistry = {
  recipeIdentityRegistry: AFENDA_RECIPE_IDENTITY_REGISTRY,
  blockRecipeIdentityRegistry: AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY,
  recipeRegistry: AFENDA_RECIPE_REGISTRY,
} as const;

export type AfendaRecipeRegistry = typeof afendaRecipeRegistry;
