/**
 * Afenda Slot Contract
 *
 * Slot owns structure.
 *
 * Purpose:
 * - Define slot authority.
 * - Govern data-slot naming and structure.
 * - Prevent components, recipes, variants, and examples from inventing slots.
 * - Keep slot identity stable for styling, testing, accessibility, and AI imitation.
 *
 * This file must not contain component logic or styling values.
 */

export const AFENDA_SLOT_CONTRACT_ID = "afenda.slot" as const;

export const AFENDA_SLOT_CONTRACT_VERSION = "0.1.0" as const;

export const AFENDA_SLOT_AUTHORITY_RULES = {
  slotOwnsStructure: true,
  slotOwnsDataSlotIdentity: true,
  slotOwnsStructuralVocabulary: true,
  slotOwnsCompositionParts: true,
} as const;

export const AFENDA_SLOT_EXACT_IDENTITY_REGISTRY = [
  "accordion",
  "accordion-content",
  "accordion-item",
  "accordion-trigger",
  "advanced-data-table-block",
  "alert",
  "alert-description",
  "alert-dialog",
  "alert-dialog-action",
  "alert-dialog-cancel",
  "alert-dialog-content",
  "alert-dialog-description",
  "alert-dialog-footer",
  "alert-dialog-header",
  "alert-dialog-overlay",
  "alert-dialog-portal",
  "alert-dialog-title",
  "alert-dialog-trigger",
  "alert-title",
  "app-nav-sidebar-content",
  "app-sidebar",
  "app-sidebar-content",
  "app-sidebar-erp-nav",
  "app-sidebar-footer",
  "app-sidebar-footer-menu",
  "app-sidebar-main-nav",
  "app-sidebar-main-nav-shell",
  "app-sidebar-nav-items",
  "app-sidebar-pinned-navigation",
  "app-sidebar-portal-nav",
  "app-sidebar-quick-actions",
  "app-sidebar-scroll",
  "app-sidebar-settings-nav",
  "app-topbar",
  "app-topbar-actions-content",
  "app-topbar-actions-trigger",
  "app-topbar-brand-disk",
  "app-topbar-left",
  "app-topbar-sidebar-trigger",
  "app-shell-sidebar-context",
  "app-topbar-context-switcher",
  "app-topbar-organization-switcher-content",
  "app-topbar-organization-switcher-trigger",
  "app-topbar-department-switcher-content",
  "app-topbar-department-switcher-trigger",
  "app-topbar-team-switcher-content",
  "app-topbar-team-switcher-trigger",
  "app-topbar-project-switcher-content",
  "app-topbar-project-switcher-trigger",
  "app-topbar-notifications-content",
  "app-topbar-right",
  "app-topbar-scope-switchers",
  "app-topbar-utilities-bar",
  "app-topbar-utilities-fixed",
  "app-topbar-utilities-market-content",
  "app-topbar-utilities-market-trigger",
  "app-topbar-utilities-rail",
  "app-topbar-utilities-request-form",
  "app-topbar-utilities-context",
  "app-topbar-utilities-sortable-horizontal",
  "app-topbar-utilities-sortable-vertical",
  "app-topbar-theme-toggle",
  "app-content",
  "app-content-body",
  "app-content-bottom-drawer",
  "app-content-bottom-drawer-trigger",
  "app-content-main",
  "app-content-header",
  "app-content-footer",
  "app-content-left-rail",
  "app-content-left-rail-trigger",
  "app-content-right-rail",
  "app-content-right-rail-trigger",
  "app-footer",
  "app-footer-link",
  "app-footer-links",
  "app-workspace-panel",
  "afenda-app-shell",
  "approval-decision-trail-block",
  "aspect-ratio",
  "audit-dock",
  "audit-evidence-workspace-block",
  "audit-safe-critical-action-block",
  "audit-trail-panel-block",
  "avatar",
  "avatar-fallback",
  "avatar-image",
  "badge",
  "batch-posting-review-block",
  "box",
  "breadcrumb",
  "breadcrumb-ellipsis",
  "breadcrumb-item",
  "breadcrumb-link",
  "breadcrumb-list",
  "breadcrumb-page",
  "breadcrumb-separator",
  "bulk-action-bar-block",
  "button",
  "button-group",
  "button-group-separator",
  "button-group-text",
  "calendar",
  "card",
  "card-action",
  "card-content",
  "card-description",
  "card-footer",
  "card-header",
  "card-title",
  "carousel",
  "carousel-content",
  "carousel-item",
  "carousel-next",
  "carousel-previous",
  "chart",
  "chart-area-interactive",
  "checkbox",
  "checkbox-indicator",
  "collapsible",
  "collapsible-content",
  "collapsible-trigger",
  "command",
  "command-empty",
  "command-group",
  "command-input",
  "command-input-wrapper",
  "command-item",
  "command-list",
  "command-search-block",
  "command-separator",
  "command-shortcut",
  "context-menu",
  "context-menu-checkbox-item",
  "context-menu-content",
  "context-menu-group",
  "context-menu-item",
  "context-menu-label",
  "context-menu-portal",
  "context-menu-radio-group",
  "context-menu-radio-item",
  "context-menu-separator",
  "context-menu-shortcut",
  "context-menu-sub",
  "context-menu-sub-content",
  "context-menu-sub-trigger",
  "context-menu-trigger",
  "dashboard-body",
  "dashboard-chrome",
  "dashboard-data-table",
  "dashboard-main-column",
  "dashboard-nav-topbar",
  "dashboard-nav-topbar-left",
  "dashboard-nav-topbar-right",
  "dashboard-page",
  "dashboard-sidebar-brand",
  "dashboard-sidebar-content",
  "dashboard-sidebar-footer",
  "dashboard-sidebar-header",
  "data-table-shell-block",
  "demo-command-filter-bar",
  "demo-site-bottom-drawer-content",
  "desktop-body",
  "desktop-page",
  "desktop-stage",
  "dialog",
  "dialog-close",
  "dialog-content",
  "dialog-description",
  "dialog-footer",
  "dialog-header",
  "dialog-overlay",
  "dialog-portal",
  "dialog-title",
  "dialog-trigger",
  "drawer",
  "drawer-close",
  "drawer-content",
  "drawer-description",
  "drawer-footer",
  "drawer-header",
  "drawer-overlay",
  "drawer-portal",
  "drawer-title",
  "drawer-trigger",
  "dropdown-menu",
  "dropdown-menu-checkbox-item",
  "dropdown-menu-content",
  "dropdown-menu-group",
  "dropdown-menu-item",
  "dropdown-menu-label",
  "dropdown-menu-portal",
  "dropdown-menu-radio-group",
  "dropdown-menu-radio-item",
  "dropdown-menu-separator",
  "dropdown-menu-shortcut",
  "dropdown-menu-sub",
  "dropdown-menu-sub-content",
  "dropdown-menu-sub-trigger",
  "dropdown-menu-trigger",
  "empty",
  "empty-content",
  "empty-description",
  "empty-header",
  "empty-media",
  "empty-panel-block",
  "empty-title",
  "entity-summary-panel-block",
  "evidence-checklist-block",
  "field",
  "field-content",
  "field-description",
  "field-error",
  "field-group",
  "field-hint",
  "field-label",
  "field-legend",
  "field-required",
  "field-separator",
  "field-separator-content",
  "field-set",
  "field-title",
  "filter-bar-block",
  "focusable",
  "form-control",
  "form-description",
  "form-item",
  "form-label",
  "form-message",
  "form-section-block",
  "grid",
  "hover-card",
  "hover-card-content",
  "hover-card-portal",
  "hover-card-trigger",
  "immutable-audit-timeline-block",
  "inline",
  "input",
  "input-group",
  "input-group-addon",
  "input-group-control",
  "input-group-text",
  "input-otp",
  "input-otp-group",
  "input-otp-separator",
  "input-otp-slot",
  "item",
  "item-actions",
  "item-content",
  "item-description",
  "item-footer",
  "item-group",
  "item-header",
  "item-media",
  "item-separator",
  "item-title",
  "kbd",
  "kbd-sequence",
  "label",
  "menubar",
  "menubar-checkbox-item",
  "menubar-content",
  "menubar-group",
  "menubar-item",
  "menubar-label",
  "menubar-menu",
  "menubar-portal",
  "menubar-radio-group",
  "menubar-radio-item",
  "menubar-separator",
  "menubar-shortcut",
  "menubar-sub",
  "menubar-sub-content",
  "menubar-sub-trigger",
  "menubar-trigger",
  "metadata-binding-diagnostic-block",
  "metadata-debug-panel-block",
  "metadata-layout-block-item",
  "metadata-layout-column",
  "metadata-layout-columns",
  "metadata-layout-group",
  "metadata-layout-tab-list",
  "metadata-layout-tab-panel",
  "metadata-layout-tabs",
  "metadata-page-layout-block",
  "metadata-page-layout-region",
  "metadata-page-renderer-block",
  "metric-text",
  "nav-documents",
  "nav-documents-more",
  "nav-main",
  "nav-main-actions",
  "nav-main-items",
  "nav-secondary",
  "nav-user",
  "nav-user-content",
  "nav-user-menu",
  "nav-user-trigger",
  "navigation-menu",
  "navigation-menu-content",
  "navigation-menu-indicator",
  "navigation-menu-item",
  "navigation-menu-link",
  "navigation-menu-list",
  "navigation-menu-trigger",
  "navigation-menu-viewport",
  "operational-dashboard-shell-block",
  "page-header-block",
  "pagination",
  "pagination-content",
  "pagination-ellipsis",
  "pagination-item",
  "pagination-link",
  "permission-action-toolbar-block",
  "policy-exception-summary-block",
  "policy-lock-manager-block",
  "popover",
  "popover-anchor",
  "popover-content",
  "popover-portal",
  "popover-trigger",
  "progress",
  "progress-indicator",
  "quality-gates-block",
  "radio-group",
  "radio-group-description",
  "radio-group-indicator",
  "radio-group-item",
  "radio-group-label",
  "radio-group-option",
  "resizable-handle",
  "resizable-panel",
  "resizable-panel-group",
  "reversible-bulk-action-bar-block",
  "risk-evidence-panel-block",
  "row-evidence-panel-block",
  "runtime-state-block",
  "save-state-strip-block",
  "scroll-area",
  "scroll-area-scrollbar",
  "scroll-area-thumb",
  "scroll-area-viewport",
  "section-cards",
  "select",
  "select-content",
  "select-group",
  "select-item",
  "select-label",
  "select-portal",
  "select-scroll-down-button",
  "select-scroll-up-button",
  "select-separator",
  "select-trigger",
  "select-value",
  "separator",
  "sheet",
  "sheet-body",
  "sheet-close",
  "sheet-content",
  "sheet-description",
  "sheet-footer",
  "sheet-header",
  "sheet-overlay",
  "sheet-portal",
  "sheet-title",
  "sheet-trigger",
  "sidebar",
  "sidebar-container",
  "sidebar-content",
  "sidebar-control-menu",
  "sidebar-control-trigger",
  "sidebar-footer",
  "sidebar-gap",
  "sidebar-group",
  "sidebar-group-action",
  "sidebar-group-content",
  "sidebar-group-label",
  "sidebar-header",
  "sidebar-inner",
  "sidebar-input",
  "sidebar-inset",
  "sidebar-menu",
  "sidebar-menu-action",
  "sidebar-menu-badge",
  "sidebar-menu-button",
  "sidebar-link",
  "sidebar-menu-item",
  "sidebar-menu-skeleton",
  "sidebar-menu-sub",
  "sidebar-menu-sub-button",
  "sidebar-menu-sub-item",
  "sidebar-rail",
  "sidebar-separator",
  "sidebar-trigger",
  "sidebar-wrapper",
  "site-body",
  "site-bottom-drawer",
  "site-container",
  "site-container-resize-bottom",
  "site-container-resize-right",
  "site-header",
  "site-main",
  "site-right-sidebar",
  "site-sidebar-left",
  "site-topbar",
  "skeleton",
  "sla-risk-escalation-panel-block",
  "slider",
  "slider-range",
  "slider-thumb",
  "slider-track",
  "spinner",
  "stack",
  "stats-strip-block",
  "status-timeline-block",
  "switch",
  "switch-thumb",
  "table",
  "table-body",
  "table-caption",
  "table-cell",
  "table-container",
  "table-footer",
  "table-head",
  "table-header",
  "table-row",
  "tabs",
  "tabs-content",
  "tabs-list",
  "tabs-trigger",
  "tenant-operations-workspace-block",
  "text",
  "textarea",
  "toaster",
  "toggle",
  "toggle-group",
  "toggle-group-item",
  "tooltip",
  "tooltip-content",
  "tooltip-portal",
  "tooltip-provider",
  "tooltip-trigger",
  "workspace-app-nav-topbar",
  "workspace-nav-site-topbar",
] as const;

export type AfendaExactSlotIdentity =
  (typeof AFENDA_SLOT_EXACT_IDENTITY_REGISTRY)[number];

export const AFENDA_SLOT_IDENTITY_PATTERN_REGISTRY = [
  "^app-topbar-[a-z0-9-]+$",
  "^app-topbar-utility-[a-z0-9-]+$",
  "^app-sidebar-[a-z0-9-]+$",
  "^nav-(secondary|main|documents)-(item|menu)-[a-z0-9-]+$",
  "^nav-main-item-[a-z0-9-]+$",
  "^section-card-[a-z0-9-]+$",
] as const;

export type AfendaSlotIdentityPattern =
  (typeof AFENDA_SLOT_IDENTITY_PATTERN_REGISTRY)[number];

export const AFENDA_SLOT_NAMING_RULES = {
  slotNamesMustUseKebabCase: true,
  dataSlotValuesMustUseKebabCase: true,
  dataSlotMustMatchContractSlotName: true,
  slotNamesMustBeStable: true,
  slotNamesMustNotEncodeStyling: true,
  slotNamesMustNotEncodeState: true,
  slotNamesMustNotEncodeBusinessMeaning: true,
} as const;

export const AFENDA_SLOT_USAGE_RULES = {
  componentsMustExposeDataSlot: true,
  componentsMustUseContractSlots: true,
  recipesMustTargetContractSlotsOnly: true,
  testsMustUseContractSlotsOnly: true,
  examplesMustUseContractSlotsOnly: true,
  unknownSlotIsHardFail: true,
} as const;

export const AFENDA_SLOT_FORBIDDEN_OWNERSHIP = {
  componentsMustNotInventSlots: true,
  recipesMustNotInventSlots: true,
  variantsMustNotInventSlots: true,
  examplesMustNotInventSlots: true,
  slotsMustNotOwnStyling: true,
  slotsMustNotOwnBehavior: true,
  slotsMustNotOwnValues: true,
  slotsMustNotOwnBusinessLogic: true,
} as const;

export const AFENDA_SLOT_CLASS_NAME_RULES = {
  slotMayExposeClassName: true,
  slotClassNameMustUseRecipe: true,
  slotClassNamePolicyIsLayoutOnly: true,
  slotClassNameMustNotOverrideSemanticIdentity: true,
} as const;

export const AFENDA_SLOT_ACCESSIBILITY_RULES = {
  structuralSlotsMustPreserveAriaRelationships: true,
  triggerContentPanelSlotsMustRemainLinked: true,
  labelControlSlotsMustRemainLinked: true,
  descriptionErrorSlotsMustRemainLinked: true,
} as const;

export const AFENDA_SLOT_FORBIDDEN_PATTERNS = [
  'data-slot="inner"',
  'data-slot="thing"',
  'data-slot="item-wrapper"',
] as const;

export const AFENDA_SLOT_SOURCE_OF_TRUTH = [
  "afenda-slot.contract.ts",
  "afenda-component.contract.ts",
  "afenda-recipe.contract.ts",
] as const;

export const AFENDA_SLOT_PRINCIPLES = [
  "slot-owns-structure",
  "slot-owns-data-slot-identity",
  "slot-names-are-stable",
  "slot-names-use-kebab-case",
  "slot-does-not-own-styling",
  "slot-does-not-own-behavior",
  "slot-does-not-own-values",
  "unknown-slot-is-hard-fail",
] as const;

export const afendaSlotContract = {
  id: AFENDA_SLOT_CONTRACT_ID,
  version: AFENDA_SLOT_CONTRACT_VERSION,
  exactSlotIdentityRegistry: AFENDA_SLOT_EXACT_IDENTITY_REGISTRY,
  slotIdentityPatternRegistry: AFENDA_SLOT_IDENTITY_PATTERN_REGISTRY,
  authorityRules: AFENDA_SLOT_AUTHORITY_RULES,
  namingRules: AFENDA_SLOT_NAMING_RULES,
  usageRules: AFENDA_SLOT_USAGE_RULES,
  forbiddenOwnership: AFENDA_SLOT_FORBIDDEN_OWNERSHIP,
  classNameRules: AFENDA_SLOT_CLASS_NAME_RULES,
  accessibilityRules: AFENDA_SLOT_ACCESSIBILITY_RULES,
  forbiddenPatterns: AFENDA_SLOT_FORBIDDEN_PATTERNS,
  sourceOfTruth: AFENDA_SLOT_SOURCE_OF_TRUTH,
  principles: AFENDA_SLOT_PRINCIPLES,
} as const;

export type AfendaSlotContract = typeof afendaSlotContract;
