export const PRIMITIVE_HARDENING_CONTRACT = {
  doctrine:
    "Afenda primitives are hardened building blocks for dense operator workflows.",
  requiredStates: [
    "default",
    "hover",
    "focus-visible",
    "active-or-pressed",
    "disabled",
    "invalid",
    "selected-open-or-checked",
    "loading-when-applicable",
    "reduced-motion",
  ],
  riskGroups: {
    forms: [
      "input",
      "textarea",
      "select",
      "checkbox",
      "radio-group",
      "switch",
      "slider",
      "input-group",
      "input-otp",
      "field",
      "form",
    ],
    overlaysAndMenus: [
      "dialog",
      "sheet",
      "drawer",
      "popover",
      "hover-card",
      "tooltip",
      "dropdown-menu",
      "context-menu",
      "menubar",
      "command",
    ],
    navigationAndData: [
      "tabs",
      "navigation-menu",
      "breadcrumb",
      "pagination",
      "sidebar",
      "table",
      "accordion",
      "collapsible",
    ],
    displayAndFeedback: [
      "alert",
      "badge",
      "card",
      "empty",
      "progress",
      "skeleton",
      "spinner",
      "sonner",
      "avatar",
      "chart",
      "carousel",
      "resizable",
      "scroll-area",
    ],
  },
  tokenPolicy: {
    rule: "Operational primitives use semantic surface, text, border, brand, and status tokens only.",
    forbiddenInPrimitives: ["warm-bark", "warm-doe", "warm-pink"],
  },
  motionPolicy: {
    rule: "Low-motion operator UI. No broad all-property transitions and no layout-property transitions in primitives.",
    allowed: [
      "background-color",
      "border-color",
      "box-shadow",
      "color",
      "opacity",
      "transform",
      "text-decoration-color",
    ],
  },
  accessibilityPolicy: {
    rule: "Radix behavior remains the accessibility foundation; Afenda adds visible focus, labels, and state clarity.",
    required: [
      "keyboard-reachable interactive controls",
      "visible focus-visible affordance",
      "accessible names for icon-only actions",
      "aria-invalid and helper or error association for invalid form states",
      "Escape closes overlays through Radix-managed primitives",
    ],
  },
} as const;
