import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { AFENDA_PUBLIC_EXPORTS } from "../contracts/afenda-export.contract.ts";
import {
  AFENDA_BLOCK_COMPONENT_IDS,
  AFENDA_COMPONENT_IDENTITY_REGISTRY,
  AFENDA_PRIMITIVE_COMPONENT_IDS,
} from "../registries/component.registry.ts";
import {
  AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY,
  AFENDA_RECIPE_IDENTITY_REGISTRY,
  AFENDA_RECIPE_REGISTRY,
} from "../registries/recipe.registry.ts";
import {
  AFENDA_SLOT_EXACT_IDENTITY_REGISTRY,
  AFENDA_SLOT_IDENTITY_PATTERN_REGISTRY,
} from "../registries/slot.registry.ts";
import {
  AFENDA_FORBIDDEN_VARIANT_ALIASES,
  AFENDA_VARIANT_ALLOWED_BY_PROP,
  AFENDA_VARIANT_IDENTITY_REGISTRY,
  AFENDA_VARIANT_PROPS,
} from "../registries/variant.registry.ts";

type StringRecord = Record<string, readonly string[]>;

const outputPath = fileURLToPath(new URL("../ai-context.ts", import.meta.url));
const checkOnly = process.argv.includes("--check");

const afendaAiContext = {
  availableComponents: {
    primitive: sortStrings(AFENDA_PRIMITIVE_COMPONENT_IDS),
    block: sortStrings(AFENDA_BLOCK_COMPONENT_IDS),
    public: sortStrings(AFENDA_COMPONENT_IDENTITY_REGISTRY),
  },
  availableSlots: {
    exact: sortStrings(AFENDA_SLOT_EXACT_IDENTITY_REGISTRY),
    patterns: sortStrings(AFENDA_SLOT_IDENTITY_PATTERN_REGISTRY),
  },
  availableVariants: {
    props: sortStrings(AFENDA_VARIANT_PROPS),
    identity: sortRecordArrays(AFENDA_VARIANT_IDENTITY_REGISTRY),
    allowedByProp: sortRecordArrays(AFENDA_VARIANT_ALLOWED_BY_PROP),
  },
  availableRecipes: {
    core: sortStrings(AFENDA_RECIPE_IDENTITY_REGISTRY),
    block: sortStrings(AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY),
    all: sortStrings(AFENDA_RECIPE_REGISTRY),
  },
  forbiddenAliases: sortRecordArrays(AFENDA_FORBIDDEN_VARIANT_ALIASES),
  publicImports: sortStrings(AFENDA_PUBLIC_EXPORTS),
} as const;

const generatedSource = [
  "// This file is generated by pnpm generate:ai-context.",
  "// Do not edit manually.",
  "",
  `export const AFENDA_AI_CONTEXT = ${JSON.stringify(
    afendaAiContext,
    null,
    2
  )} as const;`,
  "",
  "export const afendaAiContext = AFENDA_AI_CONTEXT;",
  "",
  "export type AfendaAiContext = typeof AFENDA_AI_CONTEXT;",
  "",
].join("\n");

if (checkOnly) {
  const currentSource = readFileSync(outputPath, "utf8");

  if (currentSource !== generatedSource) {
    console.error(
      "packages/design-system/ai-context.ts is stale. Run pnpm generate:ai-context."
    );
    process.exit(1);
  }

  console.log("AI context is current.");
  process.exit(0);
}

writeFileSync(outputPath, generatedSource);
console.log("Generated packages/design-system/ai-context.ts");

function sortStrings(values: readonly string[]): readonly string[] {
  return [...values].sort((a, b) => a.localeCompare(b));
}

function sortRecordArrays<TRecord extends StringRecord>(
  record: TRecord
): { readonly [TKey in keyof TRecord]: readonly string[] } {
  return Object.fromEntries(
    Object.entries(record)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, value]) => [key, sortStrings(value)])
  ) as { readonly [TKey in keyof TRecord]: readonly string[] };
}
