#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const configPath = path.join(root, ".env.config");
const secretPath = path.join(root, ".env.secret");
const dryRun = process.argv.includes("--dry-run");
const command =
  process.argv.find(
    (arg) =>
      !arg.startsWith("--") &&
      arg !== process.argv[0] &&
      arg !== process.argv[1]
  ) ?? "sync";

const generatedHeader = [
  "# Generated by scripts/sync-env.mjs.",
  "# Do not edit this file directly. Edit .env.config and .env.secret instead.",
  "",
].join("\n");

const sourceHeader = [
  "# Human-maintained local environment source.",
  "# Run `pnpm env:sync` to generate workspace .env destinations.",
  "",
].join("\n");

const secretNamePattern =
  /(^|_)(SECRET|TOKEN|PASSWORD|PRIVATE|SERVICE_ROLE|AUTH_TOKEN|WEBHOOK_SECRET|API_KEY|ACCESS_KEY|SECRET_ACCESS_KEY|DSN|DATABASE_URL)($|_)/i;

const publicNamePattern = /^(NEXT_PUBLIC_|PUBLIC_)/;

const ignoredNames = new Set(["NODE_ENV"]);

// Map next-forge .env.example keys to legacy source keys.
const envAliases = {
  RESEND_TOKEN: "RESEND_API_KEY",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: "STRIPE_PUBLISHABLE_KEY",
  NEXT_PUBLIC_API_URL: "NEXT_PUBLIC_API_URL",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "SUPABASE_ANON_PUBLIC",
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "SUPABASE_PUBLISHABLE_KEY",
};

const defaultPublicUrls = {
  NEXT_PUBLIC_API_URL: "http://localhost:3002",
  NEXT_PUBLIC_APP_URL: "http://localhost:3000",
  NEXT_PUBLIC_WEB_URL: "http://localhost:3001",
  NEXT_PUBLIC_DOCS_URL: "http://localhost:3004",
  VERCEL_PROJECT_PRODUCTION_URL: "http://localhost:3000",
};

function fail(message) {
  console.error(message);
  process.exit(1);
}

function readText(filePath) {
  return fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
}

function parseEnv(text) {
  const entries = new Map();
  const order = [];

  for (const line of text.split(/\r?\n/)) {
    const match = line.match(
      /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/
    );
    if (!match) {
      continue;
    }

    const [, key, rawValue] = match;
    if (ignoredNames.has(key)) {
      continue;
    }

    entries.set(key, rawValue.trim());
    order.push(key);
  }

  return { entries, order };
}

function parseEnvFile(filePath) {
  return parseEnv(readText(filePath));
}

function quoteValue(value) {
  const trimmed = value.trim();
  if (
    trimmed === "" ||
    trimmed.startsWith('"') ||
    trimmed.startsWith("'") ||
    /^[A-Za-z0-9_./:@%+=,-]+$/.test(trimmed)
  ) {
    return trimmed;
  }

  return `"${trimmed.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function isSecretKey(key) {
  if (publicNamePattern.test(key)) {
    return false;
  }

  return secretNamePattern.test(key);
}

function isEmptyValue(value) {
  if (value === undefined || value === null) {
    return true;
  }

  const trimmed = value.trim();
  return trimmed === "" || trimmed === '""' || trimmed === "''";
}

function collectEnvExamplePaths(dir, matches = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (
      entry.name === "node_modules" ||
      entry.name === ".git" ||
      entry.name === ".next"
    ) {
      continue;
    }

    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectEnvExamplePaths(fullPath, matches);
      continue;
    }

    if (entry.name === ".env.example") {
      matches.push(fullPath);
    }
  }

  return matches;
}

function collectExistingEnvPaths() {
  const explicitPaths = [
    ".env",
    ".env.local",
    "apps/app/.env.local",
    "apps/api/.env.local",
    "apps/web/.env.local",
    "packages/database/.env",
    "packages/cms/.env.local",
    "packages/internationalization/.env.local",
  ];

  return explicitPaths
    .map((relativePath) => path.join(root, relativePath))
    .filter((filePath) => fs.existsSync(filePath));
}

function normalizeValue(key, value) {
  if (key === "RESEND_FROM" && value.includes("<") && value.includes(">")) {
    const match = value.match(/<([^>]+)>/);
    if (match) {
      return match[1];
    }
  }

  return value;
}

function resolveValue(key, merged) {
  if (merged.has(key) && !isEmptyValue(merged.get(key))) {
    return normalizeValue(key, merged.get(key) ?? "");
  }

  const alias = envAliases[key];
  if (alias && merged.has(alias) && !isEmptyValue(merged.get(alias))) {
    return normalizeValue(key, merged.get(alias) ?? "");
  }

  if (defaultPublicUrls[key]) {
    return defaultPublicUrls[key];
  }

  return merged.get(key) ?? "";
}

function writeEnvFile(filePath, entries, keys, { omitEmpty = false } = {}) {
  const lines = [generatedHeader.trimEnd(), ""];

  for (const key of keys) {
    if (!entries.has(key)) {
      continue;
    }

    const value = entries.get(key) ?? "";
    if (omitEmpty && isEmptyValue(value)) {
      continue;
    }

    lines.push(`${key}=${quoteValue(value)}`);
  }

  const content = `${lines.join("\n")}\n`;
  const relativePath = path.relative(root, filePath) || ".env";
  if (dryRun) {
    console.log(`would write ${relativePath} (${keys.length} keys)`);
    return;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log(`wrote ${relativePath} (${keys.length} keys)`);
}

function writeSourceFile(filePath, entries, existingOrder) {
  const allKeys = Array.from(
    new Set([...existingOrder, ...entries.keys()])
  ).sort();
  const lines = [sourceHeader.trimEnd(), ""];

  for (const key of allKeys) {
    if (!entries.has(key)) {
      continue;
    }

    lines.push(`${key}=${quoteValue(entries.get(key) ?? "")}`);
  }

  const relativePath = path.relative(root, filePath);
  if (dryRun) {
    console.log(`would update ${relativePath} (${allKeys.length} keys)`);
    return;
  }

  fs.writeFileSync(filePath, `${lines.join("\n")}\n`);
  console.log(`updated ${relativePath} (${allKeys.length} keys)`);
}

function loadSources() {
  const config = parseEnvFile(configPath);
  const secret = parseEnvFile(secretPath);
  const merged = new Map([...config.entries, ...secret.entries]);

  return { config, secret, merged };
}

function getTargetPath(envExamplePath) {
  const relativeDir = path.relative(root, path.dirname(envExamplePath));
  const [workspaceType] = relativeDir.split(path.sep);
  const targetName = workspaceType === "apps" ? ".env.local" : ".env";
  if (relativeDir === "packages\\cms" || relativeDir === "packages/cms") {
    return path.join(path.dirname(envExamplePath), ".env.local");
  }
  if (
    relativeDir === "packages\\internationalization" ||
    relativeDir === "packages/internationalization"
  ) {
    return path.join(path.dirname(envExamplePath), ".env.local");
  }
  return path.join(path.dirname(envExamplePath), targetName);
}

function stripQuotes(value) {
  return value.trim().replace(/^["']|["']$/g, "");
}

function buildSupabaseDatabaseUrls(merged) {
  const password = merged.get("SUPABASE_DB_PASSWORD");
  const projectRef = merged.get("SUPABASE_PROJECT_ID");

  if (!projectRef || isEmptyValue(password ?? "")) {
    return;
  }

  const encoded = encodeURIComponent(stripQuotes(password));
  const project = stripQuotes(projectRef);
  const directUrl = `postgresql://postgres:${encoded}@db.${project}.supabase.co:5432/postgres`;

  merged.set("DIRECT_URL", directUrl);

  const poolerHost = stripQuotes(merged.get("SUPABASE_DB_POOLER_HOST") ?? "");
  if (!poolerHost) {
    if (!merged.get("DATABASE_URL") || isEmptyValue(merged.get("DATABASE_URL") ?? "")) {
      merged.set("DATABASE_URL", directUrl);
    }
    return;
  }

  const poolerMode = stripQuotes(merged.get("SUPABASE_DB_POOLER_MODE") ?? "session");
  if (poolerMode === "transaction") {
    merged.set(
      "DATABASE_URL",
      `postgresql://postgres.${project}:${encoded}@${poolerHost}:6543/postgres?pgbouncer=true`
    );
    return;
  }

  merged.set(
    "DATABASE_URL",
    `postgresql://postgres.${project}:${encoded}@${poolerHost}:5432/postgres`
  );
}

function sync() {
  const { merged } = loadSources();
  buildSupabaseDatabaseUrls(merged);
  const allKeys = Array.from(merged.keys()).sort();

  if (allKeys.length === 0) {
    fail("No keys found in .env.config or .env.secret.");
  }

  writeEnvFile(path.join(root, ".env"), merged, allKeys);
  writeEnvFile(path.join(root, ".env.local"), merged, allKeys);

  for (const examplePath of collectEnvExamplePaths(root)) {
    if (examplePath === path.join(root, ".env.example")) {
      continue;
    }

    const example = parseEnvFile(examplePath);
    const targetEntries = new Map();
    for (const key of example.order) {
      targetEntries.set(key, resolveValue(key, merged));
    }

    writeEnvFile(getTargetPath(examplePath), targetEntries, example.order, {
      omitEmpty: true,
    });
  }
}

function consolidate() {
  const { config, secret } = loadSources();
  let addedConfig = 0;
  let addedSecret = 0;

  for (const envPath of collectExistingEnvPaths()) {
    const parsed = parseEnvFile(envPath);
    for (const [key, value] of parsed.entries) {
      if (config.entries.has(key) || secret.entries.has(key)) {
        continue;
      }

      if (isSecretKey(key)) {
        secret.entries.set(key, value);
        addedSecret += 1;
      } else {
        config.entries.set(key, value);
        addedConfig += 1;
      }
    }
  }

  writeSourceFile(configPath, config.entries, config.order);
  writeSourceFile(secretPath, secret.entries, secret.order);
  console.log(
    `consolidated ${addedConfig} config keys and ${addedSecret} secret keys`
  );
}

if (command === "sync") {
  sync();
} else if (command === "consolidate") {
  consolidate();
} else if (command === "doctor") {
  const { config, secret, merged } = loadSources();
  console.log(`config keys: ${config.entries.size}`);
  console.log(`secret keys: ${secret.entries.size}`);
  console.log(`merged keys: ${merged.size}`);
  console.log(`env examples: ${collectEnvExamplePaths(root).length}`);
  const hasAccessToken = Boolean(secret.entries.get("SUPABASE_ACCESS_TOKEN"));
  const hasProjectRef = Boolean(merged.get("SUPABASE_PROJECT_ID"));
  console.log(`supabase project ref: ${hasProjectRef ? "ok" : "missing"}`);
  console.log(
    `supabase access token: ${hasAccessToken ? "ok (.env.secret)" : "missing — add SUPABASE_ACCESS_TOKEN for full auth config (pnpm supabase:auth-config)"}`
  );
  console.log(
    `supabase smtp password: ${
      secret.entries.get("SUPABASE_SMTP_PASSWORD")
        ? "ok (.env.secret)"
        : "missing — add SUPABASE_SMTP_PASSWORD for pnpm supabase:apply-smtp-config"
    }`
  );
} else {
  fail("Usage: pnpm env:sync | pnpm env:consolidate | pnpm env:doctor");
}
