import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { AFENDA_AI_CONTEXT, afendaAiContext } from "../ai-context";
import { AFENDA_PUBLIC_EXPORTS } from "../contracts/afenda-export.contract";
import {
  AFENDA_BLOCK_COMPONENT_IDS,
  AFENDA_COMPONENT_IDENTITY_REGISTRY,
  AFENDA_PRIMITIVE_COMPONENT_IDS,
} from "../registries/component.registry";
import {
  AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY,
  AFENDA_RECIPE_IDENTITY_REGISTRY,
  AFENDA_RECIPE_REGISTRY,
} from "../registries/recipe.registry";
import {
  AFENDA_SLOT_EXACT_IDENTITY_REGISTRY,
  AFENDA_SLOT_IDENTITY_PATTERN_REGISTRY,
} from "../registries/slot.registry";
import {
  AFENDA_FORBIDDEN_VARIANT_ALIASES,
  AFENDA_VARIANT_ALLOWED_BY_PROP,
  AFENDA_VARIANT_IDENTITY_REGISTRY,
  AFENDA_VARIANT_PROPS,
} from "../registries/variant.registry";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");

describe("afenda generated AI context", () => {
  it("is generated and current", () => {
    const source = readFileSync(join(packageRoot, "ai-context.ts"), "utf8");

    expect(source).toContain(
      "// This file is generated by pnpm generate:ai-context."
    );
    expect(source).toContain("// Do not edit manually.");

    execFileSync("node", ["scripts/generate-ai-context.ts", "--check"], {
      cwd: packageRoot,
      stdio: "pipe",
    });
  });

  it("matches the governed lookup sources", () => {
    expect(AFENDA_AI_CONTEXT).toEqual({
      availableComponents: {
        primitive: sortStrings(AFENDA_PRIMITIVE_COMPONENT_IDS),
        block: sortStrings(AFENDA_BLOCK_COMPONENT_IDS),
        public: sortStrings(AFENDA_COMPONENT_IDENTITY_REGISTRY),
      },
      availableSlots: {
        exact: sortStrings(AFENDA_SLOT_EXACT_IDENTITY_REGISTRY),
        patterns: sortStrings(AFENDA_SLOT_IDENTITY_PATTERN_REGISTRY),
      },
      availableVariants: {
        props: sortStrings(AFENDA_VARIANT_PROPS),
        identity: sortRecordArrays(AFENDA_VARIANT_IDENTITY_REGISTRY),
        allowedByProp: sortRecordArrays(AFENDA_VARIANT_ALLOWED_BY_PROP),
      },
      availableRecipes: {
        core: sortStrings(AFENDA_RECIPE_IDENTITY_REGISTRY),
        block: sortStrings(AFENDA_BLOCK_RECIPE_IDENTITY_REGISTRY),
        all: sortStrings(AFENDA_RECIPE_REGISTRY),
      },
      forbiddenAliases: sortRecordArrays(AFENDA_FORBIDDEN_VARIANT_ALIASES),
      publicImports: sortStrings(AFENDA_PUBLIC_EXPORTS),
    });
  });

  it("is JSON-serializable plain data", () => {
    expect(JSON.parse(JSON.stringify(afendaAiContext))).toEqual(
      afendaAiContext
    );
  });

  it("does not import component source files or runtime registries", () => {
    const source = readFileSync(join(packageRoot, "ai-context.ts"), "utf8");

    expect(source).not.toMatch(/from\s+["'][^"']*components[\\/]/);
    expect(source).not.toMatch(/from\s+["'][^"']*registries[\\/]/);
    expect(source).not.toMatch(/from\s+["'][^"']*contracts[\\/]/);
  });
});

function sortStrings(values: readonly string[]): readonly string[] {
  return [...values].sort((a, b) => a.localeCompare(b));
}

function sortRecordArrays<TRecord extends Record<string, readonly string[]>>(
  record: TRecord
): { readonly [TKey in keyof TRecord]: readonly string[] } {
  return Object.fromEntries(
    Object.entries(record)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, value]) => [key, sortStrings(value)])
  ) as { readonly [TKey in keyof TRecord]: readonly string[] };
}
